#####
# Bedroom lights
# https://www.home-assistant.io/integrations/light.group/
#####

- platform: group
  name: Leds cama
  unique_id: wled_bed_group
  entities:
    - light.wled_bed_left
    - light.wled_bed_right
    - light.wled_bed_main
