#####
# House group lights
# https://www.home-assistant.io/integrations/light.group/
#####

- platform: group
  name: Luz LED Cores
  entities:
    - light.wled_bed_group
    - light.led_strip_deck
    - light.led_strip_living_room
    - light.mi_lamp
