#####
# Command line
# https://www.home-assistant.io/integrations/command_line/
#####

- platform: command_line
  command: 'nc -z -w 5 192.168.1.21 2869 && (echo "Running") || (echo "Not running")'
  name: "Xbox One X State"
  device_class: moving
  payload_on: "Running"
  payload_off: "Not running"
  command_timeout: 5
  unique_id: xbox_one_x_state
