#####
# Ping (ICMP) component
# https://www.home-assistant.io/integrations/ping/
#####

- platform: ping
  host: 192.168.1.81
  name: "Luis Macbook on local network"
  count: 1

- platform: ping
  host: 192.168.1.82
  name: "Windows desktop state"
  count: 1
  scan_interval: 45
