homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include_dir_merge_named customize

default_config:

# ########################################
# ###                GUI               ###
# ########################################

frontend:
  # We can define additional/custom themes for the frontend here.
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources: !include_dir_list lovelace/resources
  dashboards: !include_dir_merge_named lovelace/dashboards

browser_mod:
  prefix: "browser_"
  disable:
    - all

# ########################################
# ###           INTEGRATIONS           ###
# ########################################

wake_on_lan:

# nextcloud:
#   url: http://192.168.1.90:9321
#   username: !secret nextcloud_username
#   password: !secret nextcloud_password

proxmoxve:
  - host: !secret proxmox_ip
    username: !secret proxmox_user
    password: !secret proxmox_pwd
    verify_ssl: false
    realm: pve
    nodes:
      - node: alpaca
        vms:
          - 100
          - 102
          - 103
          - 201

# ########################################
# ###          NOTIFICATIONS           ###
# ########################################

# telegram_bot:
#   - platform: polling
#     api_key: !secret telegram_bot_key
#     allowed_chat_ids:
#       - !secret telegram_chatid_luis
#       - !secret telegram_chatid_margarida

notify:
  - platform: discord
    name: discord
    token: !secret discord_bot_token

  # - platform: telegram
  #   name: Telegram Luis
  #   chat_id: !secret telegram_chatid_luis

  # - platform: telegram
  #   name: Telegram Margarida
  #   chat_id: !secret telegram_chatid_margarida

# ########################################
# ###             SERVICES             ###
# ########################################

cloud:
  # Customize the Google Assistant integration with the Nabu Casa Cloud
  google_actions:
    # Entity specific configuration for Google Assistant.
    # These are loaded from a separate directory.
    # entity_config: !include_dir_merge_named customizations/google_assistant

    # Filters for entities to include/exclude from Google Assistant.
    # These are loaded from a separate directory.
    filter:
      include_entities: !include_dir_merge_list google_assistant

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://192.168.1.95:8123
    service_name: google_say
  - platform: google_cloud
    key_file: service-account-tts.json
    language: pt-PT
    gender: male
    voice: pt-PT-Wavenet-B
    speed: 0.9
    text_type: ssml
    profiles:
      - small-bluetooth-speaker-class-device

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret spotify_dc
  sp_key: !secret spotify_key

#device_tracker:
#  - platform: bluetooth_tracker
#new_device_defaults:
#  track_new_devices: false

# ########################################
# ###              LOGGING             ###
# ########################################

logger: !include logger.yaml
recorder: !include recorder.yaml

influxdb:
  host: !secret influxdb_host
  port: 8086

  database: homeassistant
  default_measurement: state

  # Authentication credentials.
  username: !secret influxdb_username
  password: !secret influxdb_password

  # Max number of retries in case of a failure.
  max_retries: 3

  # The list of attribute names which should be reported as tags
  # and not fields to InfluxDB.
  tags_attributes:
    - device_class

  # I like to specify (whitelist) each thing I'd like to put
  # into InfluxDB, to keep the database as clean as possible.
  include:
    entities: !include_dir_merge_list influxdb

# ########################################
# ###              ENTITIES             ###
# ########################################

# media_player:
#   - platform: androidtv
#     name: Android TV
#     host: !secret android_tv_ip
#     adb_server_ip: 127.0.0.1
#     adb_server_port: 5037

#input_boolean: !include_dir_merge_named components/input_boolean
#input_datetime: !include_dir_merge_named components/input_datetime
shell_command: !include_dir_merge_named components/shell_command
sensor: !include_dir_merge_list components/sensors
binary_sensor: !include_dir_merge_list components/binary_sensors
switch: !include_dir_merge_list components/switches
light: !include_dir_merge_list components/lights
plant: !include_dir_merge_named components/plants
utility_meter: !include_dir_merge_named components/utility_meter

#group: !include_dir_merge_named groups
#automation: !include_dir_merge_list automations
automation: !include automations.yaml
#script: !include scripts.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
scene split: !include_dir_list ../scenes
