#####
# Lovelace Dashboard
# For MOBILE usage
#####

## Templates
button_card_templates: !include lovelace/templates/button_card.yaml
decluttering_templates: !include lovelace/templates/decluttering.yaml

## Dashboard settings
title: Home Control (mobile)

swipe_nav:
  wrap: false
  animate: fade
  prevent_default: true
  swipe_amount: 30

## Views
views:
  - !include lovelace/views/start-mobile.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/deck.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/ev.yaml
  #- !include lovelace/views/tasks.yaml
  #- !include lovelace/views/plants.yaml
  - !include lovelace/views/house.yaml
  - !include lovelace/views/config.yaml
  - !include lovelace/views/system-mobile.yaml
  - !include lovelace/views/network-mobile.yaml
  #- !include lovelace/views/nas.yaml
