#####
# DEFAULT Lovelace Dashboard
# For DESKTOP usage
#####

## Templates
button_card_templates: !include lovelace/templates/button_card.yaml
decluttering_templates: !include lovelace/templates/decluttering.yaml

## Dashboard settings
title: Home Control

## Views
views:
  - !include lovelace/views/start-desktop.yaml
  - !include lovelace/views/temperature.yaml
  #  - !include lovelace/views/start.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/deck.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/plants.yaml
  - !include lovelace/views/info.yaml
  - !include lovelace/views/maintenance.yaml
  - !include lovelace/views/debug.yaml
