chart:
  #height: "90px"
  fontFamily: "var(--paper-ha-card_-_font-family)"
  sparkline:
    enabled: true
tooltip:
  enabled: false
grid:
  show: false
  padding:
    left: -25
    right: -17
dataLabels:
  show: true
  offsetY: 4
  formatter: |
    EVAL:function(value) {
      if(value) {
        if(value.toFixed(1) == 0) {
          return '';
        } else {
          return value.toFixed(1) + "€";
        }
      }
    }
  style:
    fontSize: "12px"
    colors: ["var(--card-background-color)"]
  background:
    enabled: false
plotOptions:
  bar:
    borderRadius: 20
    borderRadiusApplication: "around"
    borderRadiusWhenStacked: "all"
