title: Alarme
path: security
icon: mdi:shield-home
background: "var(--background-view-security)"

type: custom:vertical-layout
layout:
  card_margin: 8px 0px
  margin: 0px
  max_width: 350
cards:
  - type: "custom:gap-card"
    height: 20

  - type: "custom:layout-card"
    layout_type: "custom:grid-layout"
    layout:
      grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr
      grid-template-rows: auto
      margin: 0px
    cards:
      - template: title
        type: "custom:decluttering-card"
        view_layout:
          grid-column: span 6
        variables:
          - content: Segurança

      - type: "custom:gap-card"
        height: 20
        view_layout:
          grid-column: span 6

      - type: "custom:alarmo-card"
        view_layout:
          grid-column: span 6
        entity: alarm_control_panel.alarmo
        button_scale_keypad: 1.5

      - type: "custom:gap-card"
        height: 20
        view_layout:
          grid-column: span 6

      - template: es-person
        type: "custom:decluttering-card"
        view_layout:
          grid-column: span 3
        variables:
          - template: person-girl
          - entity-1: input_boolean.margarida_home
          - name-1: "Ma"
          - state-1: "on"
          - state-outline: "off"

      - template: es-person
        type: "custom:decluttering-card"
        view_layout:
          grid-column: span 3
        variables:
          - template: person-man
          - entity-1: input_boolean.luis_home
          - name-1: "Lu"
          - state-1: "on"
          - state-outline: "off"

      - type: "custom:gap-card"
        height: 10
        view_layout:
          grid-column: span 6
