#####
# Custos energia
#
#####

- platform: template
  sensors:
    energy_bill:
      friendly_name: "Fatura Energia"
      device_class: monetary
      value_template: >-
        {{ ((float(states.sensor.utm_mensal_vazio.state) * (float(states.input_number.energy_cost_per_kwh_empty_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + float(states.sensor.utm_mensal_fora_de_vazio.state) * (float(states.input_number.energy_cost_per_kwh_full_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + now().day * (float(states.input_number.energy_power_cost_per_day.state) + float(states.input_number.energy_access_cost_per_day.state)) + float(states.input_number.energy_taxes.state) ) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"

- platform: template
  sensors:
    energy_bill_daily:
      friendly_name: "Fatura Energia"
      device_class: monetary
      value_template: >-
        {{ ((float(states.sensor.utm_diario_vazio.state) * (float(states.input_number.energy_cost_per_kwh_empty_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + float(states.sensor.utm_diario_fora_de_vazio.state) * (float(states.input_number.energy_cost_per_kwh_full_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + (float(states.input_number.energy_power_cost_per_day.state) + float(states.input_number.energy_access_cost_per_day.state))) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"
