#####
# Custos energia
#
#####

- platform: template
  sensors:
    energy_bill:
      friendly_name: "Fatura Energia"
      device_class: monetary
      value_template: >-
        {{ ((float(states.sensor.utm_mensal_vazio.state) * (float(states.input_number.energy_cost_per_kwh_empty_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + float(states.sensor.utm_mensal_fora_de_vazio.state) * (float(states.input_number.energy_cost_per_kwh_full_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + now().day * (float(states.input_number.energy_power_cost_per_day.state) + float(states.input_number.energy_access_cost_per_day.state)) + float(states.input_number.energy_taxes.state) ) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"

- platform: template
  sensors:
    energy_bill_daily:
      friendly_name: "Fatura Energia"
      device_class: monetary
      value_template: >-
        {{ ((float(states.sensor.utm_diario_vazio.state) * (float(states.input_number.energy_cost_per_kwh_empty_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + float(states.sensor.utm_diario_fora_de_vazio.state) * (float(states.input_number.energy_cost_per_kwh_full_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + (float(states.input_number.energy_power_cost_per_day.state) + float(states.input_number.energy_access_cost_per_day.state))) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"
# - platform: statistics
#   name: "Server daily min power"
#   entity_id: sensor.plug_3_power
#   unique_id: sensor.plug_3_power_daily_min
#   state_characteristic: value_min
#   max_age:
#     hours: 24

# - platform: statistics
#   name: "Server daily max power"
#   entity_id: sensor.plug_3_power
#   unique_id: sensor.plug_3_power_daily_max
#   state_characteristic: value_max
#   max_age:
#     hours: 24

- platform: template
  sensors:
    ibelectra_familia_simples:
      unit_of_measurement: "€/MWh"
      availability: "{{ state_attr('sensor.omie_spot_price_pt', 'today_average') != None }}"
      state_class: measurement
      state: >
        {% set OMIE = state_attr('sensor.omie_spot_price_pt', 'today_average') -%}
        {% set CGS = state_attr(this.entity_id, 'CGS') -%}
        {% set Perdas = state_attr(this.entity_id, 'Perdas') -%}
        {% set k = state_attr(this.entity_id, 'k') -%}
        {% set TAR = state_attr(this.entity_id, 'TAR') -%}

        {% if None in [CGS, Perdas, k, TAR] %}
          {{ None }}
        {% else %}
          {{ ((OMIE+CGS)*(1+Perdas)+k+TAR) | round(2) }}
        {% endif %}
      attributes:
        friendly_name: "Ibelectra Solução Familia (tarifário simples)"
        formula: (OMIE+CGS)*(1+Perdas)+k+TAR
        OMIE: "{{ state_attr('sensor.omie_spot_price_pt', 'today_average') }}"
        CGS: "{{ 7 }}"
        Perdas: "{{ 0.1604 }}"
        k: "{{ 3.5 }}"
        TAR: "{{ 36.50 }}"
        today_hours: >
          {% set OMIE = state_attr('sensor.omie_spot_price_pt', 'today_average') -%}
          {% set CGS = state_attr(this.entity_id, 'CGS') -%}
          {% set Perdas = state_attr(this.entity_id, 'Perdas') -%}
          {% set k = state_attr(this.entity_id, 'k') -%}
          {% set TAR = state_attr(this.entity_id, 'TAR') -%}

          {% set ns = namespace(hourly_data=[]) %}
          {% for h in state_attr('sensor.omie_spot_price_pt', 'today_hours') -%}
            {% if None in [OMIE, CGS, Perdas, k, TAR] %}
              {% set price = None %}
            {% else %}
              {% set price=((OMIE+CGS)*(1+Perdas)+k+TAR) | round(2) %}
            {% endif %}
            {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %}
          {% endfor -%}
          {{ dict(ns.hourly_data) }}
        tomorrow_hours: >
          {% set OMIE = state_attr('sensor.omie_spot_price_pt', 'tomorrow_average') -%}
          {% set CGS = state_attr(this.entity_id, 'CGS') -%}
          {% set Perdas = state_attr(this.entity_id, 'Perdas') -%}
          {% set k = state_attr(this.entity_id, 'k') -%}
          {% set TAR = state_attr(this.entity_id, 'TAR') -%}

          {% set ns = namespace(hourly_data=[]) %}
          {% for h in state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours') -%}
            {% if None in [OMIE, CGS, Perdas, k, TAR] %}
              {% set price=None %}
            {% else %}
              {% set price=((OMIE+CGS)*(1+Perdas)+k+TAR) | round(2) %}
            {% endif %}
            {% set ns.hourly_data=ns.hourly_data + [(h.isoformat(), price)] %}
          {% endfor -%}
          {{ dict(ns.hourly_data) }}
