#####
# Custos energia
#
#####

- platform: template
  sensors:
    energy_bill:
      friendly_name: "Fatura Energia"
      device_class: monetary
      value_template: >-
        {{ ((float(states.sensor.utm_mensal_vazio.state) * (float(states.input_number.energy_cost_per_kwh_empty_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + float(states.sensor.utm_mensal_fora_de_vazio.state) * (float(states.input_number.energy_cost_per_kwh_full_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + now().day * (float(states.input_number.energy_power_cost_per_day.state) + float(states.input_number.energy_access_cost_per_day.state)) + float(states.input_number.energy_taxes.state) ) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"

- platform: template
  sensors:
    energy_bill_daily:
      friendly_name: "Fatura Energia"
      device_class: monetary
      value_template: >-
        {{ ((float(states.sensor.utm_diario_vazio.state) * (float(states.input_number.energy_cost_per_kwh_empty_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + float(states.sensor.utm_diario_fora_de_vazio.state) * (float(states.input_number.energy_cost_per_kwh_full_hours.state) * (1-float(states.input_number.energy_discount.state)/100)) + (float(states.input_number.energy_power_cost_per_day.state) + float(states.input_number.energy_access_cost_per_day.state))) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"

# - platform: statistics
#   name: "Server daily min power"
#   entity_id: sensor.plug_3_power
#   unique_id: sensor.plug_3_power_daily_min
#   state_characteristic: value_min
#   max_age:
#     hours: 24

# - platform: statistics
#   name: "Server daily max power"
#   entity_id: sensor.plug_3_power
#   unique_id: sensor.plug_3_power_daily_max
#   state_characteristic: value_max
#   max_age:
#     hours: 24

- platform: template
  sensors:
    ibelectra_familia_simples_kwh:
      friendly_name: "Ibeletra KWh"
      value_template: >-
        {{ (states("sensor.template_ibelectra_familia_simples") | float / 1000) | float(default=0)|round(6) }}
      unit_of_measurement: "EUR/kWh"

- platform: template
  sensors:
    energy_bill_omie:
      friendly_name: "Fatura Energia Indexada"
      device_class: monetary
      value_template: >-
        {{ (( (float(states.sensor.utm_mensal_vazio.state) * float(states.sensor.ibelectra_familia_simples_kwh.state)) + (float(states.sensor.ibelectra_familia_simples_kwh.state) * float(states.sensor.ibelectra_familia_simples_kwh.state)) + (now().day * float(states.input_number.energy_access_cost_per_day.state)) + float(states.input_number.energy_taxes.state) ) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"

- platform: template
  sensors:
    energy_bill_omie_daily:
      friendly_name: "Fatura Energia diária Indexada"
      device_class: monetary
      value_template: >-
        {{ (( (float(states.sensor.utm_mensal_vazio.state) * float(states.sensor.ibelectra_familia_simples_kwh.state)) + (float(states.sensor.ibelectra_familia_simples_kwh.state) * float(states.sensor.ibelectra_familia_simples_kwh.state)) + (float(states.input_number.energy_access_cost_per_day.state))) * 1.23 ) | default(0) | round(2) }}
      unit_of_measurement: "€"
