#####
# Door sensors history
#
#####

- platform: template
  sensors:
    door_open_for:
      friendly_name: "Main door open for"
      unit_of_measurement: "minutes"
      value_template: >
        {% set t = 0 if (states('binary_sensor.openclose_1_contact') == 'off' or states('binary_sensor.openclose_1_contact') == 'unavailable') else now().timestamp() - states.binary_sensor.openclose_1_contact.last_changed.timestamp() %}
        {{ t | timestamp_custom('%M', false) | int }}

- platform: template
  sensors:
    door_open_last:
      friendly_name: "Main door lastly open"
      unit_of_measurement: "minutes"
      value_template: >
        {% set last_timestamp = states('sensor.main_door_lastly_open') %}
        {% set t = 0 if states('binary_sensor.openclose_1_contact') == 'on' else (now().timestamp() | float(0) - last_timestamp | float(0) if last_timestamp != 'unknown' else -1) %}
        {% if t == -1 %}
          -1
        {% else %}
          {% set h = t | timestamp_custom('%H', false) | int %}
          {% set m = t | timestamp_custom('%M', false) | int %}
          {{ h * 60 + m | int }}
        {% endif %}

- platform: template
  sensors:
    door_show_time:
      friendly_name: "Show door times in frontend"
      value_template: >-
        {% if now().timestamp() - as_timestamp(states('sensor.uptime')) > 3600.0 and (states('sensor.door_open_last') | int < 60 and states('sensor.door_open_last') | int >= 0) or states('sensor.door_open_for') | int > 0%}
          on
        {% else %}
          off
        {% endif %}
