#####
# Lights on counters
#
#####

- platform: template
  sensors:
    lights_on_living_room:
      friendly_name: "Luzes ligadas na Sala"
      unit_of_measurement: "on"
      value_template: >
        {% set lights = [
          states.light.led_strip_living_room,
          states.light.light_2
          ] %}
        {{ lights | selectattr('state','eq','on') | list | count }}

- platform: template
  sensors:
    lights_on_kitchen:
      friendly_name: "Luzes ligadas na Cozinha"
      unit_of_measurement: "on"
      value_template: >
        {% set lights = [
          states.light.luz_entrada,
          states.light.luz_cozinha_1,
          states.light.luz_cozinha_2,
          states.light.luz_mesa
          ] %}
        {{ lights | selectattr('state','eq','on') | list | count }}

- platform: template
  sensors:
    lights_on_bedroom_suite:
      friendly_name: "Luzes ligadas no Quarto (Suite)"
      unit_of_measurement: "on"
      value_template: >
        {% set lights = [
          states.light.bedroom_1,
          states.light.bedroom_2,
          states.light.luz_suite
          ] %}
        {{ lights | selectattr('state','eq','on') | list | count }}

- platform: template
  sensors:
    lights_on_wc_suite:
      friendly_name: "Luzes ligadas no WC (Suite)"
      unit_of_measurement: "on"
      value_template: >
        {% set lights = [
          states.light.led_wc_suite,
          states.light.extrator_wc_suite
          ] %}
        {{ lights | selectattr('state','eq','on') | list | count }}

- platform: template
  sensors:
    lights_on_bedroom_right:
      friendly_name: "Luzes ligadas no Quarto (Direita)"
      unit_of_measurement: "on"
      value_template: >
        {% set lights = [
          states.light.wled_standingdesk,
          states.light.mi_lamp_pro,
          states.light.luz_quarto_direita
          ] %}
        {{ lights | selectattr('state','eq','on') | list | count }}

- platform: template
  sensors:
    lights_on_bedroom_left:
      friendly_name: "Luzes ligadas no Quarto (Esquerda)"
      unit_of_measurement: "on"
      value_template: >
        {% set lights = [
          states.light.luz_quarto_esquerda,
          states.light.mi_lamp,
          states.light.led_strip_deck
          ] %}
        {{ lights | selectattr('state','eq','on') | list | count }}

- platform: template
  sensors:
    lights_on_house:
      friendly_name: "Luzes ligadas na casa"
      unit_of_measurement: "on"
      value_template: >
        {{ states('sensor.lights_on_bedroom_left')|int + states('sensor.lights_on_kitchen')|int + states('sensor.lights_on_living_room')|int + states('sensor.lights_on_bedroom_suite')|int + states('sensor.lights_on_bedroom_right')|int }}
