#####
# Door sensors
#
#####
- platform: template
  sensors:
    door_openclose:
      friendly_name: "Main door status"
      value_template: >-
        {% if is_state('binary_sensor.door_openclose', 'on') %}
          Aberta
        {% elif is_state('binary_sensor.door_openclose', 'off') %}
          Fechada
        {% else %}
          Erro
        {% endif %}

#####
# Presence detection
#
#####

- platform: template
  sensors:
    presence_kitchen:
      friendly_name: "Kitchen motion status"
      value_template: >-
        {% if is_state('binary_sensor.presence_kitchen', 'on') %}
          Detetado
        {% elif is_state('binary_sensor.presence_kitchen', 'off') %}
          Vazio
        {% else %}
          Erro
        {% endif %}

- platform: template
  sensors:
    presence_living_room:
      friendly_name: "Living room motion status"
      value_template: >-
        {% if is_state('binary_sensor.presence_living_room', 'on') %}
          Detetado
        {% elif is_state('binary_sensor.presence_living_room', 'off') %}
          Vazio
        {% else %}
          Erro
        {% endif %}

#####
# Water leakage
#
#####

- platform: template
  sensors:
    water_sensor:
      friendly_name: "Water leak status"
      unique_id: sensor.water_sensor
      value_template: >-
        {% if is_state('binary_sensor.water_sensor', 'off') %}
          OK
        {% elif is_state('binary_sensor.water_sensor', 'on') %}
          ALERTA
        {% else %}
          Erro
        {% endif %}

- platform: template
  sensors:
    water_sensor:
      friendly_name: "Water leak 2 status"
      unique_id: sensor.water_sensor_2
      value_template: >-
        {% if is_state('binary_sensor.water_sensor_2', 'off') %}
          OK
        {% elif is_state('binary_sensor.water_sensor_2', 'on') %}
          ALERTA
        {% else %}
          Erro
        {% endif %}
