#####
# Door sensors
#
#####
- platform: template
  sensors:
    door_openclose:
      friendly_name: "Main door status"
      value_template: >-
        {% if is_state('binary_sensor.openclose_main_contact', 'on') %}
          Aberta
        {% elif is_state('binary_sensor.openclose_main_contact', 'off') %}
          Fechada
        {% else %}
          Erro
        {% endif %}
