#####
# Door sensors
#
#####
- platform: template
  sensors:
    door_openclose:
      friendly_name: "Main door status"
      value_template: >-
        {% if is_state('binary_sensor.openclose_main_contact', 'on') %}
          Aberta
        {% elif is_state('binary_sensor.openclose_main_contact', 'off') %}
          Fechada
        {% else %}
          Erro
        {% endif %}

#####
# Presence detection
#
#####

- platform: template
  sensors:
    presence_kitchen:
      friendly_name: "Kitchen motion status"
      value_template: >-
        {% if is_state('binary_sensor.presence_2_occupancy', 'on') %}
          Detetado
        {% elif is_state('binary_sensor.presence_2_occupancy', 'off') %}
          Vazio
        {% else %}
          Erro
        {% endif %}

- platform: template
  sensors:
    presence_hall:
      friendly_name: "Living room motion status"
      value_template: >-
        {% if is_state('binary_sensor.presence_hall_motion', 'on') %}
          Detetado
        {% elif is_state('binary_sensor.presence_hall_motion', 'off') %}
          Vazio
        {% else %}
          Erro
        {% endif %}

- platform: template
  sensors:
    presence_bedroom_right:
      friendly_name: "Bedroom right motion status"
      value_template: >-
        {% if is_state('binary_sensor.human_presence_1_presence', 'on') %}
          Detetado
        {% elif is_state('binary_sensor.human_presence_1_presence', 'off') %}
          Vazio
        {% else %}
          Erro
        {% endif %}

- platform: template
  sensors:
    presence_bedroom_left:
      friendly_name: "Bedroom left motion status"
      value_template: >-
        {% if is_state('binary_sensor.occupancy_sensor_c56f_occupancy', 'on') %}
          Detetado
        {% elif is_state('binary_sensor.occupancy_sensor_c56f_occupancy', 'off') %}
          Vazio
        {% else %}
          Erro
        {% endif %}
