#####
# System Monitor component
# https://www.home-assistant.io/integrations/systemmonitor
#####

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  scan_interval: 60
  value_template: "{{ value | multiply(0.001) | round(1) }}"
