#####
# Version component for local copy
# https://www.home-assistant.io/integrations/version/
#####

- platform: version
  name: Current Version
  source: local

  
#####
# Version component for hassio - newest release
# https://www.home-assistant.io/integrations/version/
#####

- platform: version
  name: Latest Version
  source: hassio
