####
# CONFIG
# HA devices
#
####
type: vertical-stack
view_layout:
  grid-column: span 6
cards:
  - type: vertical-stack
    cards:
      - type: "custom:gap-card"
        height: 25

      - type: "custom:decluttering-card"
        template: subtitle
        variables:
          - content: Bateria dos sensores

      - type: "custom:auto-entities"
        card:
          columns: 1
          height: 17px
          severity:
            - color: "#FF0000"
              from: 0
              to: 10
            - color: "#FF6600"
              from: 11
              to: 20
            - color: "#FF9933"
              from: 21
              to: 30
            - color: "#FFCC00"
              from: 31
              to: 40
            - color: "#FFDB60"
              from: 41
              to: 50
            - color: "#FFDB60"
              from: 51
              to: 60
            - color: "#FFDB60"
              from: 61
              to: 70
            - color: "#CCFF33"
              from: 71
              to: 80
            - color: "#66FF33"
              from: 81
              to: 90
            - color: "#279B37"
              from: 91
              to: 100
          positions:
            icon: "off"
            name: outside
          type: "custom:bar-card"
          unit_of_mesurement: "%"
          card_mod:
            style: |-
              bar-card-row {
                margin-bottom: 0px !important;
              }
              ha-card {
                background: var(--ha-card-background-es-static);
                font-weight: bold;
                color: var(--el-es-static-text-color);
                font-size: 12px;
              }
              bar-card-card {
                --bar-card-border-radius: 5px;
              }
              bar-card-value {
                color: var(--el-es-static-text-color);
                margin-right: auto;
                font-size: 12px;
                font-weight: bold;
                text-shadow: 1px 1px #0005;
              }
              bar-card-backgroundbar {
                opacity: 0.1;
              }
          width: 40%
        sort:
          method: state
          numeric: true
        filter:
          include:
            - attributes:
                device_class: battery
              domain: sensor
              state: "<= 50"
          exclude:
            - name: "*[Oo]neplus*"
            - name: "*[Oo]ppo*"
            - name: "*HUAWEI*"
            - name: "*[Mm]acbook*"
            - name: "sensor.browser_*"
            - name: "sensor.nexus_7_*"

  - type: vertical-stack
    cards:
      - type: "custom:gap-card"
        height: 25

      - type: "custom:decluttering-card"
        template: subtitle
        variables:
          - content: Estatisticas

      - type: entities
        entities:
          - entity: sensor.devices
            name: Devices
          - entity: sensor.entities
            name: Entities
          - entity: sensor.integrations
            name: Integrations
          - sensor.custom_integrations
          - entity: sensor.alarm_control_panels
            name: Alarm control panels
          - entity: sensor.areas
            name: Areas
          - entity: sensor.zones
            name: Zones
          - entity: sensor.device_trackers
            name: Device trackers
          - entity: sensor.automations
            name: Automations
          - entity: sensor.scenes
            name: Scenes
          - entity: sensor.scripts
            name: Scripts
          - entity: sensor.binary_sensors
            name: Binary sensors
          - entity: sensor.cameras
            name: Cameras
          - entity: sensor.climate
            name: Climate
          - entity: sensor.covers
            name: Covers
          - entity: sensor.input_booleans
            name: Input booleans
          - entity: sensor.input_buttons
            name: Input buttons
          - entity: sensor.input_datetimes
            name: Input date/times
          - entity: sensor.input_numbers
            name: Input numbers
          - entity: sensor.input_selects
            name: Input selects
          - entity: sensor.input_texts
            name: Input texts
          - entity: sensor.lights
            name: Lights
          - entity: sensor.media_players
            name: Media players
          - entity: sensor.numbers
            name: Numbers
          - entity: sensor.persons
            name: Persons
          - entity: sensor.sensors
            name: Sensors
          - entity: sensor.switches
            name: Switches
        state_color: true
        card_mod:
          style: !include ../styles/style-card-entities-img.yaml
